// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPi7MccyZOStMhf6jfl09mIEzgDICob_k',
    appId: '1:306481167547:android:630c00423a9107dea37d9e',
    messagingSenderId: '306481167547',
    projectId: 'smart-cane-b946d',
    storageBucket: 'smart-cane-b946d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM3cTMDx8hf1CSLc0C3MgGeiW3DpSXypk',
    appId: '1:702709402883:ios:442231a74477184a4d2d36',
    messagingSenderId: '702709402883',
    projectId: 'smart-garden-cd3b0',
    storageBucket: 'smart-garden-cd3b0.appspot.com',
    iosBundleId: 'com.example.smart-garden.dev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFgobRZTp_oL-bNJnM4tg8PurbInWLwI',
    appId: '1:306481167547:web:0bed6caf4a59cde9a37d9e',
    messagingSenderId: '306481167547',
    projectId: 'smart-cane-b946d',
    authDomain: 'smart-cane-b946d.firebaseapp.com',
    storageBucket: 'smart-cane-b946d.appspot.com',
  );

}